document.title='STREETWISE · Robot learning on Central Avenue';
import './style.css';
import {ForkScene} from './scene';
import {ACTIONS,DURATION,scenario,simulate,observation,type Action,type Episode} from './simulation';
import {choose,forecast,type Evaluation,type Forecast,type UpdateResult,type Focus} from './learning';
import {type WorldModel} from './model';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div class="fork-app"><header class="topbar"><a class="brand" href="?fork=1">STREETWISE<span>CHENNAI / WORLD MODEL LAB</span></a><div class="topnote">Imagine. Act. Learn.</div><a class="map-link" href="?district=central-avenue">Explore the original map ↗</a></header>
<main class="workspace"><section class="world"><div class="scene-wrap"><canvas id="fork-scene" aria-label="Chennai robot encounter: actual positions and translucent model predictions"></canvas><div class="scene-title"><span class="eyebrow">CENTRAL AVENUE · SYNTHETIC ENCOUNTER</span><h1>One decision.<br>Three possible futures.</h1><p>Move around the van. Anticipate the crossing.</p></div><div class="scene-tools"><button id="camera-reset" title="Reset camera">Reset camera ↗</button><span id="scene-state">Loading mapped neighborhood…</span></div><div class="scene-legend"><span><i class="solid"></i>Actual</span><span><i class="ghost"></i>Predicted</span><span>Observer view · pedestrian can be hidden from robot</span></div><div id="scene-error" class="scene-error" hidden></div></div>
<div class="branches" aria-label="Choose a predicted future">${ACTIONS.map((a,i)=>`<button class="branch" data-action="${a}" aria-pressed="false"><div class="branch-heading"><span class="branch-number">0${i+1}</span><strong>${['Continue','Slow & look','Wait, then go'][i]}</strong><span class="chosen-tag"></span></div><canvas width="340" height="160" aria-label="${a} predicted paths"></canvas><div class="branch-stats"><span class="clearance">—</span><span class="progress">—</span></div></button>`).join('')}</div>
<div class="transport"><button id="play" class="primary" disabled>Run chosen action ▶</button><label class="timeline"><span class="sr-only">Replay time</span><input id="scrubber" aria-label="Replay time" type="range" min="0" max="6" step="0.05" value="0"><span id="time">0.0 / 6.0 s</span></label><button id="replay" title="Replay from start" disabled>↺</button></div><div class="result-line" id="outcome" role="status">Predictions use a last-seen track. The simulator determines the outcome.</div></section>
<aside class="inspector"><section><div class="section-label">01 / SET THE ENCOUNTER</div><label class="slider-label" for="speed">Pedestrian speed <output id="speed-value">1.15 m/s</output></label><input id="speed" type="range" min="0.65" max="1.75" step="0.05" value="1.15"><label class="slider-label" for="crossing">Crossing offset <output id="crossing-value">0.00 m</output></label><input id="crossing" type="range" min="-0.75" max="0.75" step="0.05" value="0"><label class="slider-label" for="hesitation">Hidden hesitation <output id="hesitation-value">0.45 s</output></label><input id="hesitation" type="range" min="0.1" max="0.75" step="0.05" value="0.45"><p class="muted">Hesitation changes the simulator. It is never supplied to the predictor.</p><button id="new-scenario" class="secondary" disabled>New encounter ↗</button></section>
<section><div class="section-label">02 / LEARN FROM THE MISS</div><div class="model-heading"><h2 id="model-version">Preparing model</h2><span id="samples">Local CPU</span></div><p class="muted">Three fitted dynamics predictors imagine six seconds from the same observation.</p><button id="learn" class="primary" disabled>Learn from this run ↗</button><p id="learning-state" role="status">Training the initial model on 12 synthetic scenarios…</p><ol class="loop"><li data-phase="observe">Observe</li><li data-phase="imagine">Imagine</li><li data-phase="act">Act</li><li data-phase="evaluate">Evaluate</li><li data-phase="learn">Learn</li></ol></section>
<section class="evaluation"><div class="section-label">03 / SEALED EVALUATION · 64 SCENARIOS</div><div class="metric"><span>Forecast error <small>Lower is better</small></span><strong id="rmse">—</strong></div><div class="comparison"><span>Initial model <b id="initial-rmse">—</b></span><span>Constant velocity <b id="baseline-rmse">—</b></span></div><div class="metric"><span>Simulated contacts <small>Selected actions</small></span><strong id="contacts">—</strong></div><div class="comparison"><span>Completed <b id="completion">—</b></span><span>CV contacts <b id="baseline-contacts">—</b></span></div><button id="export" class="text-button" disabled>Download experiment report ↓</button></section>
<details><summary>Model, evidence & limits</summary><p>This is a fitted random-feature ensemble: learned output weights predict robot and pedestrian positions given a last-seen track, proposed action and time horizon. It is not a pretrained video model.</p><p>Training, promotion validation and sealed test seeds are disjoint. Promotion requires lower validation error and no increase in simulated contacts. Ensemble spread is a heuristic, not calibrated confidence.</p><p>Pedestrians, robot behavior and van placement are synthetic. Chennai building footprints use OpenStreetMap; dimensions and architectural details remain inferred. This is a navigation experiment, not G1 motor control or real-world safety validation.</p><p>The exact robot action schedule and constant pedestrian velocity form the baseline. Completion means clearing the crossing by 1 m within six seconds without contact.</p></details>
<section class="telemetry"><div class="section-label">EXPERIMENT CONNECTION</div><p id="telemetry-status">Checking local W&B service…</p><a id="telemetry-link" hidden target="_blank" rel="noopener">Open experiment ↗</a><p id="analyst-status" class="muted"></p><a href="http://127.0.0.1:2718" target="_blank" rel="noopener">Open marimo experiment lab ↗</a></section></aside></main>
<footer class="bottomline"><span>STREETWISE / Learn before the next move.</span><span>Map © OpenStreetMap contributors · synthetic behavior</span></footer></div>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const worker=new Worker(new URL('./learning.worker.ts',import.meta.url),{type:'module'});let taskId=0;
const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
function job<T>(type:string,payload:Record<string,unknown>={}):Promise<T>{return new Promise((resolve,reject)=>{const id=++taskId,timer=setTimeout(()=>{pending.delete(id);reject(new Error('Training timed out. Reload to restart the worker.'));},60000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,type,...payload});});}
worker.onmessage=e=>{const p=pending.get(e.data.id);if(!p)return;clearTimeout(p.timer);pending.delete(e.data.id);e.data.error?p.reject(new Error(e.data.error)):p.resolve(e.data.result);};
worker.onerror=()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('Model worker failed. Reload to try again.'));}pending.clear();};
let scene:ForkScene;let model:WorldModel|null=null,test:Evaluation|null=null,initial:Evaluation|null=null,fs:Forecast[]=[],selected:Action='continue',episode:Episode|null=null,runFinished=false,busy=false,seed=42;
const recorded=new Set<string>();const runs:Episode[]=[],updates:Omit<UpdateResult,'model'|'candidate'>[]=[];let telemetryAvailable=false;let analyst:Record<string,unknown>|null=null;
function phase(name:string){document.querySelectorAll('.loop li').forEach(e=>e.classList.toggle('active',(e as HTMLElement).dataset.phase===name));}
function scenarioNow(){return {...scenario(seed),speed:Number($<HTMLInputElement>('speed').value),crossing:Number($<HTMLInputElement>('crossing').value),hesitation:Number($<HTMLInputElement>('hesitation').value)};}
function report(){return {schema:'fork-experiment-v1',createdAt:new Date().toISOString(),model:{version:model?.version,samples:model?.samples,trainingSeeds:model?.trainingSeeds},checkpoint:model,initial,test,updates,runs:runs.map(e=>({scenario:e.scenario,action:e.action,observation:e.observation,contact:e.contact,minClearance:e.minClearance,progress:e.progress,states:e.states})),analyst,limits:'Synthetic kinematic scenario. No real pedestrian calibration, G1 control or physical safety validation.'};}
function setButtons(){const ready=!!model&&!!scene?.frame&&!busy&&!scene?.error;$<HTMLButtonElement>('play').disabled=!ready;$<HTMLButtonElement>('replay').disabled=!ready;$<HTMLButtonElement>('learn').disabled=!ready||!runFinished;$<HTMLButtonElement>('new-scenario').disabled=!ready;$<HTMLButtonElement>('export').disabled=!model;for(const id of ['speed','crossing','hesitation','scrubber'])$<HTMLInputElement>(id).disabled=busy;document.querySelectorAll<HTMLButtonElement>('.branch').forEach(b=>b.disabled=!ready);}
function showMetrics(){if(!model||!test)return;$('model-version').textContent=`World model v${model.version}`;$('samples').textContent=`${model.samples.toLocaleString()} samples`;$('rmse').textContent=`${test.learned.forecastRMSE.toFixed(3)} m`;$('initial-rmse').textContent=`${initial?.learned.forecastRMSE.toFixed(3)} m`;$('baseline-rmse').textContent=`${test.baseline.forecastRMSE.toFixed(3)} m`;$('contacts').textContent=`${test.learned.contacts} / ${test.learned.episodes}`;$('baseline-contacts').textContent=`${test.baseline.contacts} / ${test.baseline.episodes}`;$('completion').textContent=`${test.learned.completion} / ${test.learned.episodes}`;}
function select(a:Action){if(!model||!scene.frame)return;selected=a;episode=simulate(scenarioNow(),a);scene.setEpisode(episode,fs.find(f=>f.action===a)!);runFinished=false;$('play').textContent='Run chosen action ▶';$('outcome').textContent='Solid actors are simulator state; translucent actors and dashed paths are predictions.';document.querySelectorAll<HTMLButtonElement>('.branch').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.action===a)));$<HTMLInputElement>('scrubber').value='0';$('time').textContent='0.0 / 6.0 s';setButtons();phase('imagine');}
function predictAll(){if(!model||!scene.frame)return;const o=observation(scenarioNow());fs=ACTIONS.map(a=>forecast(model,o,a));const recommended=choose(fs);document.querySelectorAll<HTMLButtonElement>('.branch').forEach((b,i)=>{b.querySelector('.clearance')!.textContent=`${fs[i].clearance.toFixed(2)} m clearance`;b.querySelector('.progress')!.textContent=`${fs[i].progress.toFixed(1)} m travel`;b.querySelector('.chosen-tag')!.textContent=fs[i].action===recommended?'CHOSEN':'';});scene.setPreviews([...document.querySelectorAll<HTMLCanvasElement>('.branch canvas')],fs);select(recommended);}
function finish(){if(!episode||runFinished)return;runFinished=true;const signature=JSON.stringify([episode.scenario,episode.action]);if(!recorded.has(signature)){recorded.add(signature);runs.push(episode);if(runs.length>30)runs.shift();}const index=Math.round(scene.time/.05),p=fs.find(f=>f.action===selected)!.points[index],s=episode.states[index],error=Math.hypot(p[2]-s.pn,p[3]-s.ps);$('outcome').textContent=`${episode.contact?'Contact in simulator':'No contact in simulator'} · ${episode.minClearance.toFixed(2)} m minimum clearance · ${error.toFixed(2)} m final pedestrian error`;$('play').textContent='Replay action ▶';phase('evaluate');setButtons();void publish();}
function play(){if(!episode)return;if(scene.running){scene.running=false;$('play').textContent='Resume ▶';return;}if(scene.time>=DURATION){scene.seek(0);runFinished=false;}scene.running=true;$('play').textContent='Pause Ⅱ';phase('act');}
async function api(path:string,body?:unknown){const response=await fetch('/fork-api'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(path==='/analyze'?35000:12000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Telemetry service unavailable');return data;}
async function publish(){if(!telemetryAvailable)return;try{const r=await api('/runs',report());$('telemetry-status').textContent=r.status||'Experiment recorded';if(r.url){const a=$<HTMLAnchorElement>('telemetry-link');a.href=r.url;a.hidden=false;}}catch{$('telemetry-status').textContent='Could not sync. Local report is available to download.';}}
async function learn(){if(!model||busy)return;busy=true;scene.running=false;setButtons();phase('learn');$('learning-state').textContent='Collecting new synthetic scenarios and fitting a candidate…';
 try{let focus:Focus='balanced';if(telemetryAvailable){$('analyst-status').textContent='W&B analyst is reviewing the experiment…';try{analyst=await api('/analyze',{modelVersion:model.version,recent:runs.slice(-3).map(e=>({action:e.action,scenario:e.scenario,contact:e.contact,minClearance:e.minClearance}))});if(['balanced','fast','slow','hesitation'].includes(String(analyst?.focus)))focus=analyst!.focus as Focus;$('analyst-status').textContent=String(analyst?.summary||'Analysis recorded.')+` Training focus: ${focus}.`;}catch{$('analyst-status').textContent='Analyst unavailable; continuing with the local curriculum.';}}
 const r=await job<UpdateResult>('improve',{model,episodes:runs,focus});model=r.model;test=r.test;const {model:_,candidate:__,...summary}=r;updates.push(summary);$('learning-state').textContent=`${r.promoted?'Promoted':'Kept current model'}: ${r.reason} Validation error ${r.validationBefore.forecastRMSE.toFixed(3)} → ${r.validationAfter.forecastRMSE.toFixed(3)} m.`;showMetrics();save();predictAll();phase('evaluate');await publish();
 }catch(e){$('learning-state').textContent=`Update failed: ${e instanceof Error?e.message:String(e)}. Current model retained.`;}finally{busy=false;setButtons();}}
function save(){try{localStorage.setItem('fork-model-v1',JSON.stringify({model,test,initial,updates}));}catch{$('learning-state').textContent+=' Browser storage unavailable; download the report to keep results.';}}
async function init(){
 try{scene=new ForkScene($<HTMLCanvasElement>('fork-scene'));scene.onTime=t=>{$<HTMLInputElement>('scrubber').value=String(t);$('time').textContent=`${t.toFixed(1)} / 6.0 s`;if(episode){const s=episode.states[Math.min(120,Math.round(t/.05))];$('scene-state').textContent=s.visible?'Pedestrian visible to robot':'Pedestrian occluded · prediction uses last-seen track';}if(t>=6)finish();};
 const loading=job<{model:WorldModel;test:Evaluation}>('bootstrap');await scene.ready;const r=await loading;model=r.model;test=r.test;initial=r.test;
 try{const saved=JSON.parse(localStorage.getItem('fork-model-v1')||'null');if(saved?.model?.version>1&&saved.model.members?.length===3&&saved.model.trainingSeeds?.every((s:unknown)=>Number.isInteger(s)&&Number(s)>0&&Number(s)<10000)){const checked=await job<Evaluation>('evaluate',{model:saved.model});model=saved.model;test=checked;updates.push(...(Array.isArray(saved.updates)?saved.updates.slice(-10):[]));}}catch{localStorage.removeItem('fork-model-v1');}
 showMetrics();predictAll();$('learning-state').textContent=model!.version>1?'Restored your learned model and re-evaluated it on the sealed scenarios.':'Initial model ready. Run an encounter, then learn from the result.';setButtons();$('scene-state').textContent=`${scene.coverage.toLocaleString()} mapped buildings · last-seen track ready`;
 (window as any).fork={scene,get model(){return model;},get evaluation(){return test;},get forecasts(){return fs;},get episode(){return episode;},get report(){return report();},predictAll,learn,select};
 }catch(e){$('scene-error').hidden=false;$('scene-error').textContent=`FORK could not start: ${e instanceof Error?e.message:String(e)}. Reload to retry.`;$('learning-state').textContent='Startup failed. No model results are available.';setButtons();}
}
$('play').onclick=play;$('learn').onclick=()=>void learn();$('replay').onclick=()=>{scene.running=false;scene.seek(0);runFinished=false;$('play').textContent='Run chosen action ▶';setButtons();};$('camera-reset').onclick=()=>scene?.resetCamera();
$<HTMLInputElement>('scrubber').oninput=e=>{scene.running=false;scene.seek(Number((e.target as HTMLInputElement).value));$('play').textContent='Resume ▶';};
for(const id of ['speed','crossing','hesitation'])$<HTMLInputElement>(id).oninput=()=>{const value=Number($<HTMLInputElement>(id).value);$(id+'-value').textContent=`${value.toFixed(2)} ${id==='speed'?'m/s':id==='hesitation'?'s':'m'}`;predictAll();};
$('new-scenario').onclick=()=>{seed=seed>=9998?42:seed+1;const s=scenario(seed);for(const id of ['speed','crossing','hesitation'] as const){$<HTMLInputElement>(id).value=String(s[id]);$(id+'-value').textContent=`${Number($<HTMLInputElement>(id).value).toFixed(2)} ${id==='speed'?'m/s':id==='hesitation'?'s':'m'}`;}predictAll();};
document.querySelectorAll<HTMLButtonElement>('.branch').forEach(b=>b.onclick=()=>select(b.dataset.action as Action));
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`fork-experiment-v${model?.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
void api('/health').then(r=>{telemetryAvailable=true;$('telemetry-status').textContent=r.connected?'W&B connected through local service':r.configured?'W&B connection unavailable · local reports still work':'Local service ready · W&B key not configured';}).catch(()=>{$('telemetry-status').textContent='Local mode · start telemetry service to connect W&B';});
void init();
