document.title='STREETWISE · Robot learning on Central Avenue';
import './style.css';
import './robot.css';
import {installLiveLab} from './live-lab';
import {readRecorded} from './live-api';
import type {ValidationPoint} from './live-api';
import * as THREE from 'three';
import {ForkScene} from './scene';
import {applyCentralAvenueRealism,createCentralAvenueRender} from './realism';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';
import {UnitreeG1} from './g1';
type Frame={condition?:string;seek_shelter?:boolean;emergencies?:{kind:string;position:number[];yaw:number;active:boolean;visible:boolean}[];people?:{position:number[];direction:number;visible:boolean}[];t:number;qpos:number[];pedestrian:number[];action:number;visible:boolean;clearance:number;hazard?:string;hazard_position?:number[]};
type Replay={shelters?:number[][];seek_shelter?:boolean;goal?:number[];people?:{start:number;v:number}[];condition?:string;road_friction?:number;visibility_range?:number;difficulty?:number;hazard?:string;seed:number;frames:Frame[];outcome:{fall?:boolean;physical_contact?:boolean;first_violation_time?:number|null;safe_stop?:boolean;success:boolean;contact:boolean;elapsed:number;min_clearance:number;hazard?:string;hazard_position?:number[]};scenario:{speed:number;hesitation:number;crossing:number;start:number}};
type Mode='before'|'after';
if(new URLSearchParams(location.search).has('embed'))document.body.classList.add('embedded-replay');
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div class="robot-app"><header class="topbar"><a class="brand" href="?robot=1">STREETWISE<span>CHENNAI / ROBOT LEARNING LAB</span></a><span class="topnote">The same street. A better decision.</span><nav><a href="?compare=1">Compare policies</a><a href="?fork=1">World model</a><a href="https://molab.marimo.io/notebooks/nb_gK678riXiVKWuUAnQjffef" target="_blank" rel="noopener">marimo lab ↗</a></nav></header>
<main><div class="robot-scene"><canvas id="g1-scene" aria-label="Official Unitree G1 model replaying recorded MuJoCo physics on Central Avenue"></canvas><div class="cinema-shade"></div><div class="robot-title"><span class="eyebrow">KANAKADHARA · CENTRAL AVENUE · MUJOCO</span><h1>Learn to wait.<br>Then find a way.</h1><p>Reinforcement learning for the decisions<br>between a walking robot and a changing street.</p></div><div class="replay-badge"><i></i><span id="replay-source">Loading verified physics replays…</span></div><div class="mode-switch" role="group" aria-label="Before and after reinforcement learning"><button id="before" aria-pressed="true">01 / Before RL</button><button id="after" aria-pressed="false">02 / After RL</button></div><div class="robot-live"><span id="robot-command">Loading Unitree policy…</span><strong id="robot-event">Preparing the encounter</strong><span id="robot-sensor">Observer camera</span></div><button id="cinema" title="Toggle clean camera view">Cinema view ⛶</button><div id="robot-error" hidden role="alert"></div></div>
<div class="robot-transport"><button class="primary" id="robot-play" disabled>Play encounter ▶</button><label class="timeline"><span class="sr-only">Replay time</span><input type="range" id="robot-time" aria-label="Replay time" min="0" max="12" step=".02" value="0"><span id="robot-clock">0.0 s</span></label><label class="seed-control">Curriculum <select id="curriculum"><option value="crossing">Pedestrian crossing</option><option value="hazards-latest">Traffic · retrained with contact checks</option><option value="rain-shelter">Rain onset → seek shelter</option><option value="hazards">Original traffic · audited</option><option value="weather">Original wet-road crossing · audited</option></select></label><label class="seed-control">Test scenario <select id="robot-seed" disabled></select></label><button id="camera" class="secondary">Reset camera ↗</button></div>
<section class="robot-evidence"><div class="evidence-title"><span class="eyebrow">HELD-OUT EVIDENCE</span><h2>Did the robot improve?</h2><p>Same 64 unseen encounters. Same frozen Unitree gait.<br>Only the learned navigation policy changes.</p><a id="wandb-run" target="_blank" rel="noopener">Open W&B experiment ↗</a></div><div class="robot-metrics"><div><span>Tasks completed</span><strong id="success-comparison">Evaluating…</strong><small>Before → after</small></div><div><span>Safety violations</span><strong id="contact-comparison">Evaluating…</strong><small>Clearance envelope or audited physical contact</small></div><div><span>Robot falls</span><strong id="fall-comparison">Evaluating…</strong><small>MuJoCo physics</small></div></div><div class="curve-wrap"><span class="eyebrow">PPO VALIDATION CURVE</span><canvas id="rl-curve" width="650" height="230" aria-label="Measured validation success rate during PPO training"></canvas><small id="curve-source">Measured training checkpoints · test seeds excluded from selection</small></div></section>
<details class="robot-method"><summary>What was trained, what was reused, and how to reproduce it</summary><p>Unitree's official G1 12-DoF LSTM locomotion policy drives the joints through MuJoCo. PPO learns when to command 0, 0.35, or 0.7 m/s at 5 Hz. The expanded curriculum also adds left and right velocity options. Cars follow synthetic crossing paths; marked road defects are keep-out zones without physical terrain deformation. The base locomotion weights remain frozen. The Unitree SDK2 integration is separately verified through 500 CRC-checked LowCmd messages applied to simulated joints and 500 LowState feedback messages on loopback.</p><p>Rewards favor completing the crossing and penalize clearance violations, falls, and timeouts. Validation seeds select a checkpoint; the held-out test set reports the selected policy's outcome. The before policy commands a constant 0.7 m/s. You can inspect any of the 64 test encounters above.</p><p>The scene reuses the existing photo-informed Chennai map and OpenStreetMap footprints. MuJoCo uses an inferred Central Avenue corridor and a synthetic van and pedestrian. Published benchmarks use recorded MuJoCo trajectories. The new-encounter controls run fresh MuJoCo on the server and play the resulting joint motion here. Neither mode is a physical G1 trial or a calibrated digital twin. Source, checkpoints, SDK evidence, and run instructions are in the submission package.</p></details></main><footer class="bottomline"><span>STREETWISE / Imagine. Act. Evaluate. Learn.</span><span>Map © OpenStreetMap contributors · G1 © Unitree Robotics · simulation only</span></footer></div>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const scene=new ForkScene($<HTMLCanvasElement>('g1-scene')),g1=new UnitreeG1(),physical=new THREE.Group();
let dataOrigin='recorded';
let mode:Mode='before',data:{before:Replay[];after:Replay[]}|null=null,current:Replay|null=null,time=0,playing=false,last=0;
let movingCar:THREE.Group,roadDefect:THREE.Group;let rain:THREE.LineSegments;const payloads:Record<string,any>={};
const emergencyModels:THREE.Group[]=[];
const extraHumans:THREE.Group[]=[],extraMixers:THREE.AnimationMixer[]=[],shelterModels:THREE.Group[]=[];
let human:THREE.Group,humanMixer:THREE.AnimationMixer;let walkDuration=1;
const methods={scene,g1,get human(){return human;},select,seek,play:()=>{playing=true;},pause:()=>{playing=false;},get current(){return current;},get time(){return time;},get mode(){return mode;},curriculum:loadCurriculum};
(window as any).forkRobot=methods;
async function createHuman(){const model=await new FBXLoader().loadAsync('/assets/fork/pedestrian/walking-human.fbx');const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());model.scale.setScalar(1.72/size.y);model.rotation.x=Math.PI/2;model.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=o.receiveShadow=true;}});humanMixer=new THREE.AnimationMixer(model);const clip=model.animations.find(a=>/walk/i.test(a.name))||model.animations[0];if(!clip)throw new Error('Human FBX has no walking animation');walkDuration=clip.duration;humanMixer.clipAction(clip).play();const group=new THREE.Group();group.add(model);return group;}
async function createVan(){const asset=await new GLTFLoader().loadAsync('/assets/central-avenue-passenger-van.glb');const model=asset.scene;model.quaternion.setFromAxisAngle(new THREE.Vector3(0,0,1),Math.PI/2).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2));model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const wrapper=new THREE.Group();wrapper.add(model);wrapper.scale.set(4.7/size.x,1.7/size.y,2.15/size.z);model.position.sub(center);model.position.z+=size.z/2;wrapper.position.set(-3.1,-2,0);model.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=o.receiveShadow=true;}});return wrapper;}
async function createMovingCar(){const asset=await new GLTFLoader().loadAsync('/assets/encaarpus-parked-car.glb');const model=asset.scene;model.rotation.x=Math.PI/2;model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.position.z+=size.z/2;const wrapper=new THREE.Group();wrapper.add(model);wrapper.scale.set(1.7/size.x,4.1/size.y,1.44/size.z);model.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=o.receiveShadow=true;});return wrapper;}
function createShelter(){const g=new THREE.Group();const material=new THREE.MeshStandardMaterial({color:0x477963,roughness:.85});const roof=new THREE.Mesh(new THREE.BoxGeometry(1.4,1.3,.12),material);roof.position.z=2.65;roof.castShadow=true;g.add(roof);for(const x of [-.65,.65]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,2.6,8),new THREE.MeshStandardMaterial({color:0x687b73,metalness:.5,roughness:.6}));pole.rotation.x=Math.PI/2;pole.position.set(x,.58,1.3);pole.castShadow=true;g.add(pole);}g.visible=false;return g;}
function createEmergencyModels(){
 const person=new THREE.Group(),debris=new THREE.Group();
 const cloth=new THREE.MeshStandardMaterial({color:0x3d5c80,roughness:.95}),skin=new THREE.MeshStandardMaterial({color:0x85573b,roughness:.95}),trousers=new THREE.MeshStandardMaterial({color:0x303642,roughness:.95});
 function capsule(group:THREE.Group,a:number[],b:number[],radius:number,material:THREE.Material){const start=new THREE.Vector3(...a as [number,number,number]),end=new THREE.Vector3(...b as [number,number,number]);const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(radius,start.distanceTo(end),4,10),material);mesh.position.copy(start).add(end).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),end.sub(start).normalize());mesh.castShadow=true;group.add(mesh);}
 capsule(person,[-.30,0,.23],[.28,0,.23],.20,cloth);
 const head=new THREE.Mesh(new THREE.SphereGeometry(.16,12,10),skin);head.position.set(.66,0,.20);head.castShadow=true;person.add(head);
 for(const side of [-1,1]){capsule(person,[-.28,side*.11,.16],[-.82,side*.19,.12],.09,trousers);capsule(person,[.23,side*.19,.18],[-.20,side*.28,.13],.065,cloth);}
 const concrete=new THREE.MeshStandardMaterial({color:0x787366,roughness:1});
 for(const [x,y,sx,sy,sz,yaw] of [[0,0,.31,.23,.16,0],[.37,.18,.17,.17,.22,20],[-.39,-.18,.16,.18,.12,-15],[.12,-.30,.19,.12,.09,12]]){const mesh=new THREE.Mesh(new THREE.BoxGeometry(sx*2,sy*2,sz*2),concrete);mesh.position.set(x,y,sz);mesh.rotation.z=yaw*Math.PI/180;mesh.castShadow=mesh.receiveShadow=true;debris.add(mesh);}
 person.visible=debris.visible=false;return [person,debris];
}
function createRoadDefect(){const group=new THREE.Group();for(const [inner,outer,color] of [[0,.36,0x282521],[.36,.55,0x746b59]]){const mesh=new THREE.Mesh(inner?new THREE.RingGeometry(inner,outer,19):new THREE.CircleGeometry(outer,19),new THREE.MeshStandardMaterial({color,roughness:1,side:THREE.DoubleSide}));mesh.position.z=.015;group.add(mesh);}for(const y of [-.38,.38]){const cone=new THREE.Mesh(new THREE.ConeGeometry(.085,.23,12),new THREE.MeshStandardMaterial({color:0xdb7031,roughness:.85}));cone.rotation.x=Math.PI/2;cone.position.set(0,y,.13);cone.castShadow=true;group.add(cone);}return group;}
async function loadCurriculum(key:string){playing=false;dataOrigin='recorded';for(const id of ['robot-seed','before','after','robot-play'])$(id).setAttribute('disabled','');try{if(!payloads[key]){const response=await fetch(key==='rain-shelter'?'/assets/fork/rain-shelter-experiment.json':key==='hazards-latest'?'/assets/fork/hazard-contact-experiment.json':key==='streetlife'?'/assets/fork/streetlife-experiment.json':key.startsWith('weather-level-')?`/assets/fork/${key}-experiment.json`:key==='weather'?'/assets/fork/weather-experiment.json':key==='hazards'?'/assets/fork/hazard-experiment.json':'/assets/fork/robot-experiment.json');if(!response.ok)throw new Error('This curriculum is not available yet. The pedestrian replay remains available.');payloads[key]=await readRecorded(response);}const payload=payloads[key];data=payload.replays;$<HTMLSelectElement>('curriculum').value=key;const picker=$<HTMLSelectElement>('robot-seed');picker.replaceChildren();for(const r of data!.before){const o=document.createElement('option');o.value=String(r.seed);o.textContent=`${r.seed}${r.hazard?' · '+r.hazard.replaceAll('_',' '):''}${r.condition?' · '+r.condition:''}`;picker.append(o);}picker.value=String(data!.before.find(r=>r.outcome.contact&&data!.after.find(a=>a.seed===r.seed)?.outcome.success)?.seed||data!.before[0].seed);const e=payload.evaluation;$('success-comparison').textContent=`${Math.round(e.baseline.success_rate*64)} → ${Math.round(e.trained.success_rate*64)} / 64`;$('contact-comparison').textContent=`${e.baseline.clearance_violations} → ${e.trained.clearance_violations}`;$('fall-comparison').textContent=`${e.baseline.falls} → ${e.trained.falls}`;$<HTMLAnchorElement>('wandb-run').href=e.wandbUrl||'https://github.com/KaushikSiva/g1-street-wise';drawCurve(e.history);if(payload.contactAudit)$('curve-source').textContent='Original clearance-only training curve; outcomes corrected by recorded-contact audit.';$('robot-error').hidden=true;select('before');}catch(error){$('robot-error').hidden=false;$('robot-error').textContent=String(error);}finally{for(const id of ['robot-seed','before','after','robot-play'])$(id).removeAttribute('disabled');}}
function select(next:Mode,seed=Number($<HTMLSelectElement>('robot-seed').value)){if(!data)return;mode=next;current=data[mode].find(r=>r.seed===seed)||data[mode][0];time=0;playing=false;$<HTMLSelectElement>('robot-seed').value=String(current.seed);for(const m of ['before','after'])$(m).setAttribute('aria-pressed',String(m===mode));$<HTMLInputElement>('robot-time').max=String(current.frames.at(-1)!.t);$('replay-source').textContent=`${dataOrigin==='fresh_mujoco'?'FRESH MUJOCO RUN':'RECORDED MUJOCO'} · SEED ${current.seed}${current.condition?' · '+current.condition.toUpperCase():''}`;$('robot-play').textContent='Play encounter ▶';scene.scene.fog=current.condition==='fog'?new THREE.FogExp2(0xb8c2c4,.045):current.condition==='rain'?new THREE.FogExp2(0x919fa5,.013):null;rain.visible=current.condition==='rain';for(let i=0;i<shelterModels.length;i++){const p=current.shelters?.[i];shelterModels[i].visible=!!p;if(p)shelterModels[i].position.set(p[0],p[1],0);}seek(0);}
function seek(t:number){if(!current)return;time=Math.max(0,Math.min(t,current.frames.at(-1)!.t));const i=Math.min(current.frames.length-1,Math.round(time/.02)),f=current.frames[i];g1.pose(f.qpos);if(f.condition)rain.visible=f.condition==='rain';for(let j=0;j<emergencyModels.length;j++){const a=f.emergencies?.[j];emergencyModels[j].visible=!!a?.active;if(a){emergencyModels[j].position.set(...a.position as [number,number,number]);emergencyModels[j].rotation.z=a.yaw;}}if(rain?.visible){const a=rain.geometry.attributes.position as THREE.BufferAttribute;for(let k=0;k<a.count;k+=2){const z=((k*.173-time*8)%14+14)%14;a.setZ(k,z);a.setZ(k+1,z-.28);}a.needsUpdate=true;}human.position.set(f.pedestrian[0],f.pedestrian[1],0);human.rotation.z=Math.PI;const kind=current.hazard||'pedestrian';human.visible=kind==='pedestrian';movingCar.visible=kind==='moving_car';roadDefect.visible=kind==='pothole_zone';const hp=f.hazard_position||f.pedestrian;movingCar.position.set(hp[0],hp[1],0);roadDefect.position.set(hp[0],0,0);for(let k=0;k<extraHumans.length;k++){const actor=f.people?.[k];extraHumans[k].visible=!!actor;if(actor){extraHumans[k].position.set(actor.position[0],actor.position[1],0);extraHumans[k].rotation.z=actor.direction<0?0:Math.PI;extraMixers[k].setTime((Math.abs(actor.position[1]-(current.people?.[k]?.start||0))/.8)%walkDuration);}}humanMixer.setTime(((f.pedestrian[1]-current.scenario.start)/.8)%walkDuration);$<HTMLInputElement>('robot-time').value=String(time);$('robot-clock').textContent=`${time.toFixed(1)} / ${current.frames.at(-1)!.t.toFixed(1)} s`;$('robot-command').textContent=`${mode==='before'?'CONSTANT FORWARD':'PPO NAVIGATION'} · ${['WAIT','0.35 m/s','0.70 m/s','STEER LEFT','STEER RIGHT','MOVE LEFT','MOVE RIGHT','BACKWARD'][f.action]}`;$('robot-sensor').textContent=kind==='pothole_zone'?'Detected road defect · avoidance zone':f.visible?`${kind==='moving_car'?'Car':'Pedestrian'} visible to robot`:'Occluded actor · last-seen track';if(current.condition)$('robot-sensor').textContent+=` · friction ${current.road_friction?.toFixed(2)} · tracking ${current.visibility_range?.toFixed(1)} m`;const done=time>=current.frames.at(-1)!.t-.01;const failed=current.outcome.contact&&time>=(current.outcome.first_violation_time??current.outcome.elapsed);const seeking=f.seek_shelter??current.seek_shelter;$('robot-event').textContent=failed?(current.outcome.physical_contact?'Failed · physical collision':'Failed · clearance violated'):done?(current.outcome.success?(current.outcome.safe_stop?'Stopped clear of the accident':current.seek_shelter?'Shelter reached':'Crossing completed'):current.outcome.contact?'Clearance envelope violated':'Crossing incomplete'):(seeking?(f.action===0?'Waiting safely near cover':'Rain · navigating toward shelter'):f.action===0?'Waiting for the crossing':f.action>=3?'Steering around the hazard':f.action===1?'Approaching with care':'Moving toward the crossing');$('robot-event').classList.toggle('violation',failed);}
function camera(){if(!scene.frame)return;scene.camera.fov=48;scene.camera.updateProjectionMatrix();scene.camera.position.copy(scene.frame.point(66,-4,2.8));scene.controls.target.copy(scene.frame.point(74,3,1.3));scene.controls.minDistance=2.8;scene.controls.update();}
function drawCurve(history:ValidationPoint[]){const canvas=$<HTMLCanvasElement>('rl-curve'),c=canvas.getContext('2d')!;c.clearRect(0,0,650,230);c.font='13px Arial';c.fillStyle='#768477';c.strokeStyle='#cdd3c9';for(let k=0;k<=4;k++){const y=190-k*40;c.beginPath();c.moveTo(40,y);c.lineTo(630,y);c.stroke();c.fillText(`${k*25}%`,0,y+4);}const max=Math.max(...history.map(r=>r.step),1);c.strokeStyle='#286653';c.lineWidth=3;c.beginPath();history.forEach((r,i)=>{const x=40+590*r.step/max,y=190-160*r['validation/success_rate'];if(i===0)c.moveTo(x,y);else c.lineTo(x,y);});c.stroke();c.fillText('0 steps',40,221);c.fillText(`${max.toLocaleString()} steps`,515,221);}
async function init(){try{const [_,__,response,person,van,hdr,car]=await Promise.all([scene.ready,g1.load(),fetch('/assets/fork/robot-experiment.json'),createHuman(),createVan(),new RGBELoader().loadAsync('/assets/textures/central-daylight.hdr'),createMovingCar()]);hdr.mapping=THREE.EquirectangularReflectionMapping;scene.scene.environment=hdr;scene.scene.environmentIntensity=.4;if(!response.ok)throw new Error('Robot evaluation is still being prepared. Reload when training finishes.');const payload=await readRecorded(response);payloads.crossing=payload;data=payload.replays;scene.scene.remove(scene.stage);const f=scene.frame!,origin=f.point(75,0,.07);physical.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(f.direction,f.normal.clone().negate(),new THREE.Vector3(0,1,0)));physical.position.copy(origin);movingCar=car;roadDefect=createRoadDefect();const drops=[];for(let i=0;i<600;i++){const x=((i*7.13)%40)-20,y=((i*3.37)%24)-12,z=(i*.173)%14;drops.push(x,y,z,x+.025,y,z-.28);}const rainGeometry=new THREE.BufferGeometry();rainGeometry.setAttribute('position',new THREE.Float32BufferAttribute(drops,3));rain=new THREE.LineSegments(rainGeometry,new THREE.LineBasicMaterial({color:0xbfcbd5,transparent:true,opacity:.55}));rain.visible=false;physical.add(g1.group,van,movingCar,roadDefect,rain);human=person;physical.add(human);for(let i=0;i<2;i++){const model=cloneSkeleton(human.children[0]) as THREE.Group;const group=new THREE.Group();group.add(model);group.visible=false;extraHumans.push(group);const mixer=new THREE.AnimationMixer(model);const clip=human.children[0].animations.find(a=>/walk/i.test(a.name))||human.children[0].animations[0];mixer.clipAction(clip).play();extraMixers.push(mixer);physical.add(group);}for(let i=0;i<3;i++){const shelter=createShelter();shelterModels.push(shelter);physical.add(shelter);}emergencyModels.push(...createEmergencyModels());physical.add(...emergencyModels);scene.scene.add(physical);scene.renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.renderer.toneMappingExposure=1.05;await applyCentralAvenueRealism(scene.scene,scene.renderer,scene.frame!);scene.renderFrame=createCentralAvenueRender(scene.scene,scene.renderer,scene.camera).render;camera();
 const picker=$<HTMLSelectElement>('robot-seed');for(const r of data!.before){const option=document.createElement('option');option.value=String(r.seed);option.textContent=String(r.seed);picker.append(option);}const illustration=data!.before.find(r=>r.outcome.contact&&data!.after.find(a=>a.seed===r.seed)?.outcome.success);picker.value=String(illustration?.seed||data!.before[0].seed);picker.disabled=false;
 const e=payload.evaluation;$('success-comparison').textContent=`${Math.round(e.baseline.success_rate*64)} → ${Math.round(e.trained.success_rate*64)} / 64`;$('contact-comparison').textContent=`${e.baseline.clearance_violations} → ${e.trained.clearance_violations}`;$('fall-comparison').textContent=`${e.baseline.falls} → ${e.trained.falls}`;if(e.wandbUrl)$<HTMLAnchorElement>('wandb-run').href=e.wandbUrl||'https://github.com/KaushikSiva/g1-street-wise';drawCurve(e.history);$<HTMLButtonElement>('robot-play').disabled=false;select('before');(window as any).forkRobot.ready=true;if(!new URLSearchParams(location.search).has('embed'))installLiveLab(result=>{data=result.replays;dataOrigin=result.source;const picker=$<HTMLSelectElement>('robot-seed');picker.replaceChildren(new Option(String(result.seed),String(result.seed)));select('after',result.seed);});
 }catch(error){$('robot-error').hidden=false;$('robot-error').textContent=error instanceof Error?error.message:String(error);}}
function animate(t:number){if(playing&&current){seek(time+Math.min(.08,(t-last)/1000));if(time>=current.frames.at(-1)!.t){playing=false;$('robot-play').textContent='Replay encounter ▶';}}last=t;requestAnimationFrame(animate);}requestAnimationFrame(animate);
$<HTMLSelectElement>('curriculum').onchange=e=>void loadCurriculum((e.target as HTMLSelectElement).value);$('before').onclick=()=>select('before');$('after').onclick=()=>select('after');$<HTMLSelectElement>('robot-seed').onchange=()=>select(mode);$('camera').onclick=camera;$('robot-play').onclick=()=>{if(!current)return;if(time>=current.frames.at(-1)!.t)seek(0);playing=!playing;$('robot-play').textContent=playing?'Pause Ⅱ':'Resume ▶';};$<HTMLInputElement>('robot-time').oninput=e=>{playing=false;seek(Number((e.target as HTMLInputElement).value));$('robot-play').textContent='Resume ▶';};$('cinema').onclick=()=>document.body.classList.toggle('cinema');void init();
